"project_identifier" : "binary-bot"
api_key_env: CROWDIN_API_KEY

files:
  - 
    source: /src/common/translations/en/*.json
    translation: /src/common/translations/%locale_with_underscore%/%original_file_name%
