orbs:
  docker: circleci/docker@0.5.13
  gcp-gke: circleci/gcp-gke@0.2.0
version: 2.1
jobs:
  build_binary_bot:
    machine: true
    steps:
#      - checkout
#      - run:
#          name: Install dependency
#          command: npm i
#      - run:
#          name: Perform unit tests
#          command: npm test
#      - run:
#          name: Build code
#          command: npm run build-min
#      - docker/build:
#          image: gokulakrishna/binary-bot
#      - docker/check
#      - docker/push:
#          image: gokulakrishna/binary-bot
      - gcp-gke/init
      - gcp-gke/rollout-image:
          cluster: binary-bot-circleci-cluster
          deployment: binary-bot-circleci-deployment
          container: binary-bot
          image: gokulakrishna/binary-bot
workflows:
  deploy_kubernetes:
    jobs:
      - build_binary_bot
