orbs:
  docker: circleci/docker@0.5.13
  gcp-gke: circleci/gcp-gke@0.2.0
  gcp-gcr: circleci/gcp-gcr@0.6.1
version: 2.1
jobs:
  build_binary_bot:
    machine: true
    steps:
#      - checkout
#      - run:
#          name: Install dependency
#          command: npm i
#      - run:
#          name: Perform unit tests
#          command: npm test
#      - run:
#          name: Build code
#          command: npm run build-min
#      - docker/build:
#          image: gokulakrishna/binary-bot
#      - docker/check
#      - docker/push:
#          image: gokulakrishna/binary-bot
      - gcp-gke/init
      - gcp-gke/install
      - gcp-gcr/gcr-auth
      - run:
          name: Install auth
          command: gcloud container clusters get-credentials binary-bot-circleci
      - run:
          name: Deploy GCP
          command: kubectl create deployment new-deployment --image=docker.io/gokulakrishna/binary-bot:62148a0ff665da4c8a41c5c35544842df987608e
workflows:
  deploy_kubernetes:
    jobs:
      - build_binary_bot
