version: 2
jobs:
  build:
    machine: true
    #docker:
    #  - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: Install dependency
          command: npm i
      - run:
          name: Perform unit tests
          command: npm test
      - run:
          name: Build code
          command: npm run build-min
      - run:
          name: Build image
          command: docker build -t binary-bot-nginx .  
      - run:
          name: Tag Image
          command: docker tag binary-bot-nginx gcr.io/binary-exchange-development/binary-bot-nginx:latest
      - run:
          name: Push Image to GCP
          command: docker push gcr.io/binary-exchange-development/binary-bot-nginx:latest
