orbs:
  gcp-gcr: circleci/gcp-gcr@0.6.1
version: 2.1
jobs:
  build:
    machine: true
    #docker:
    #  - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: Install dependency
          command: npm i
      - run:
          name: Perform unit tests
          command: npm test
      - run:
          name: Build code
          command: npm run build-min
          #- run:
          #name: Build image
          # command: docker build -t binary-bot-nginx .  
      - gcp-gcr/build-image:
          image: binary-bot-nginx
      - run:
          name: Tag Image
          command: docker tag binary-bot-nginx gcr.io/${GCP_PROJECT}/${IMAGE_NAME}:latest
          #      - run:
          #name: Push Image to GCP
          #command: docker push gcr.io/${GCP_PROJECT}/${IMAGE_NAME}:latest
